### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [JoshuaBedford/lando-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by JoshuaBedford** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.
> 
> Please add a license file - if you don't have one in mind, I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.
> 
> Thanks!

@unixorn Thanks for reaching out! I've reconfigured a bit and added a license file. Let me know if any other changes need to or can be made to make this better! I'll close it but feel free to respond.

**Comment by unixorn** [comment]
Thanks, adding in https://github.com/unixorn/awesome-zsh-plugins/pull/829
