### ISSUE TITLE
Other Project Directory.

### ISSUE THREAD

**Issue by devajmeireles** [JoshuaBedford/lando-zsh#3]
Hi!

My website projects are in "/media/SSD/Workspace/Private /". How can I use this plugin for ZSH? For example, I have a project where `.lando.yml` is in: "/media/SSD/Workspace/Private/School/base" (because in this project I have `base` folder and `cdn` folder, that's an API for CDN image).

When I use `artisan` inside the `base` directory (where I have .lando.yml) it doesn't work. 

Do I need to adjust something? I saw that `$LANDO_ZSH_SITES_DIRECTORY` pointed me to /home/user/Sites where I don't have any sites.

**Comment by devajmeireles** [comment]
I solved this by changing `$LANDO_ZSH_SITES_DIRECTORY` to ` /media/SSD/Workspace/Private`. I think the documentation can be improved because of this.

**Comment by JoshuaBedford** [comment]
@ajmeireles Thanks for the feedback! I'll look into improving the documentation on how to make it more understandable on changing it to your own environment.

**Comment by devajmeireles** [comment]
> @ajmeireles Thanks for the feedback! I'll look into improving the documentation on how to make it more understandable on changing it to your own environment.

I've sent a PR improving the readme.md
